---

- name: --- GET INFO using CLI ---
  hosts: esnog_arista
  gather_facts: false
  
  vars_files:
    - ./../group_vars/arista.yml

  tasks:

# ----------------------------------
#   USING COMMAND and JSON
# ----------------------------------      


  - name: GATHERING INFO using CLI
     arista.eos.eos_command:
         commands: "show ver | json"
      register: SHOW_VER


  # ------------- SHOW VERSION
  
  - name: SHOW VER - EOS VERSION (json)
     debug:
       msg: SHOW VER using JSON = {{ inventory_hostname }} - {{ SHOW_VER.stdout[0]["version"] }}


  # ------------- MODEL NAME  & SERIAL NUMBER

  - name: SHOW SERIAL NUMBER (json)
     debug:
        msg: SHOW SERIAL NUMBER using JSON = {{ inventory_hostname }}  - {{ SHOW_VER.stdout[0]["modelName"] }}  - {{ SHOW_VER.stdout[0]["serialNumber"] }}
