#  Playbook to WIPE all Arista Devices and reset to default values

---

- name: --- ARISTA WIPE CONFIG & RESET TO DEFAULT VALUES ---
  gather_facts: false
  
  hosts: carlos_lab

  vars_files:
    - ./../group_vars/arista.yml 

  tasks:

#  -----  Saved Configs (TAC and rollback)

    - name: DELETE - saved tech-support
      arista.eos.eos_command:
        commands:
          - delete /recursive flash:/schedule/*
      ignore_errors: true

    - name: DELETE - saved TAC tech-support
      arista.eos.eos_command:
        commands:
          - delete flash:/*tech*.*
      ignore_errors: true

    - name: DELETE - ROLLBACK files
      arista.eos.eos_command:
        commands:
          - delete flash:/rollback*
      ignore_errors: true

    - name: DELETE - CHECKPOINT files
      arista.eos.eos_command:
        commands:
          - delete checkpoint:/*
      ignore_errors: true

    - name: DEACTIVATE - schedule tech-support
      arista.eos.eos_config:
        lines:
          - no schedule tech-support
      ignore_errors: true


# ----- SSH/SSL CERTIFICATES & FILES

    - name: DELETE - applied SSLKeys
      arista.eos.eos_command:
        commands:
          - delete sslkey:/*
      ignore_errors: true

    - name: DELETE - SSL files
      arista.eos.eos_command:
        commands:
          - delete flash:/*ssl*.*
      ignore_errors: true

    - name: DELETE - Certificate files (.crt)
      arista.eos.eos_command:
        commands:
          - delete certificate:/*
      ignore_errors: true

    - name: DELETE - Certificate files (.ca)
      arista.eos.eos_command:
        commands:
          - delete ssh-ca-key:/*
      ignore_errors: true


#  -----  DELETE current configuration

    - name: DELETE current configuration
      arista.eos.eos_command:
        commands:
          - write erase now


#  -----  RELOAD

    - name: reboot switch
      eos_command:
        commands:
          - reload now force
